package com.zallpy.Desafio_unicred.exception.holder;

public class CustomException extends RuntimeException{

    public CustomException(String message) {
        super(message);
    }
}
